In [1]:
import numpy as np

In [5]:
a = np.random.random((15,3))
a

array([[0.38833928, 0.71805154, 0.45716532],
       [0.03202688, 0.2088577 , 0.95708386],
       [0.3538163 , 0.611712  , 0.27611118],
       [0.37083927, 0.29249635, 0.07777021],
       [0.19903508, 0.26768326, 0.15485987],
       [0.95752289, 0.06523056, 0.67571626],
       [0.03414438, 0.14584092, 0.23083532],
       [0.55923025, 0.84475885, 0.95633204],
       [0.97121332, 0.99076438, 0.44571347],
       [0.9449733 , 0.65894714, 0.32909692],
       [0.43266079, 0.30991724, 0.00503056],
       [0.88438284, 0.51003968, 0.14313835],
       [0.18037738, 0.18065399, 0.59962809],
       [0.97790521, 0.90816951, 0.69802637],
       [0.50082265, 0.32597524, 0.16694101]])

In [8]:
print(a.shape)
print(a.size)

(15, 3)
45


In [9]:
b = np.random.random((5,2,3))
print(b)

[[[0.40543891 0.22149223 0.11330903]
  [0.04557022 0.93536638 0.33022929]]

 [[0.33066908 0.92652586 0.10422807]
  [0.49285866 0.93317635 0.08480978]]

 [[0.93910071 0.88839171 0.32800856]
  [0.76622762 0.77106513 0.69918289]]

 [[0.15357208 0.93495718 0.96006815]
  [0.71579154 0.59437824 0.49114719]]

 [[0.56428354 0.86769721 0.35160727]
  [0.87451097 0.00220814 0.90140021]]]


In [11]:
c = np.random.random((3, 2, 4, 5))
c

array([[[[0.31024015, 0.10379996, 0.45108301, 0.87348686, 0.97503934],
         [0.8327406 , 0.25936296, 0.2375512 , 0.47393628, 0.59209941],
         [0.23198515, 0.53466818, 0.55913997, 0.29844697, 0.62099801],
         [0.38823417, 0.70645047, 0.14150713, 0.47794682, 0.54939046]],

        [[0.53976314, 0.53120056, 0.57738488, 0.01169558, 0.77128118],
         [0.85126244, 0.04283652, 0.03726557, 0.75749606, 0.24630321],
         [0.89218131, 0.81023714, 0.98536603, 0.09309156, 0.85504858],
         [0.86363777, 0.56479927, 0.89458388, 0.10239363, 0.68995892]]],


       [[[0.33590851, 0.33622085, 0.11173928, 0.56439431, 0.58807089],
         [0.5938345 , 0.56731563, 0.80982999, 0.4754457 , 0.81614833],
         [0.86809126, 0.00468082, 0.10043566, 0.84422456, 0.96802587],
         [0.48544154, 0.76221579, 0.55794415, 0.18294985, 0.88781897]],

        [[0.83912678, 0.47185968, 0.40012494, 0.80582715, 0.94006158],
         [0.58514992, 0.81623245, 0.46327403, 0.90536525, 0.69053979]

In [12]:
a

array([[0.38833928, 0.71805154, 0.45716532],
       [0.03202688, 0.2088577 , 0.95708386],
       [0.3538163 , 0.611712  , 0.27611118],
       [0.37083927, 0.29249635, 0.07777021],
       [0.19903508, 0.26768326, 0.15485987],
       [0.95752289, 0.06523056, 0.67571626],
       [0.03414438, 0.14584092, 0.23083532],
       [0.55923025, 0.84475885, 0.95633204],
       [0.97121332, 0.99076438, 0.44571347],
       [0.9449733 , 0.65894714, 0.32909692],
       [0.43266079, 0.30991724, 0.00503056],
       [0.88438284, 0.51003968, 0.14313835],
       [0.18037738, 0.18065399, 0.59962809],
       [0.97790521, 0.90816951, 0.69802637],
       [0.50082265, 0.32597524, 0.16694101]])

In [23]:
a[1, :]

array([0.03202688, 0.2088577 , 0.95708386])

In [25]:
a[4,1]

0.267683261282597

In [28]:
lst_lst = [[1,2,3], [4,5,6], [7,8,9]]
d = np.array(lst_lst)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
#Sum all elements in matrix a

print(np.sum(a))

#Sum each column in matrix a

print(np.sum(a, axis = 0))

#Sum each row in matrix a

print(np.sum(a, axis =1 ))

#Sum all elements in the first two groups of array b

np.sum(b[:2])

20.99983703899083
[7.78728982 7.03909838 6.17344884]
[1.56355615 1.19796845 1.24163948 0.74110584 0.62157821 1.69846971
 0.41082062 2.36032114 2.40769117 1.93301736 0.74760859 1.53756087
 0.96065946 2.58410109 0.9937389 ]


4.923673853940289

In [34]:
b

array([[[0.40543891, 0.22149223, 0.11330903],
        [0.04557022, 0.93536638, 0.33022929]],

       [[0.33066908, 0.92652586, 0.10422807],
        [0.49285866, 0.93317635, 0.08480978]],

       [[0.93910071, 0.88839171, 0.32800856],
        [0.76622762, 0.77106513, 0.69918289]],

       [[0.15357208, 0.93495718, 0.96006815],
        [0.71579154, 0.59437824, 0.49114719]],

       [[0.56428354, 0.86769721, 0.35160727],
        [0.87451097, 0.00220814, 0.90140021]]])

In [36]:
b[:3]

array([[[0.40543891, 0.22149223, 0.11330903],
        [0.04557022, 0.93536638, 0.33022929]],

       [[0.33066908, 0.92652586, 0.10422807],
        [0.49285866, 0.93317635, 0.08480978]],

       [[0.93910071, 0.88839171, 0.32800856],
        [0.76622762, 0.77106513, 0.69918289]]])

In [37]:
c

array([[[[0.31024015, 0.10379996, 0.45108301, 0.87348686, 0.97503934],
         [0.8327406 , 0.25936296, 0.2375512 , 0.47393628, 0.59209941],
         [0.23198515, 0.53466818, 0.55913997, 0.29844697, 0.62099801],
         [0.38823417, 0.70645047, 0.14150713, 0.47794682, 0.54939046]],

        [[0.53976314, 0.53120056, 0.57738488, 0.01169558, 0.77128118],
         [0.85126244, 0.04283652, 0.03726557, 0.75749606, 0.24630321],
         [0.89218131, 0.81023714, 0.98536603, 0.09309156, 0.85504858],
         [0.86363777, 0.56479927, 0.89458388, 0.10239363, 0.68995892]]],


       [[[0.33590851, 0.33622085, 0.11173928, 0.56439431, 0.58807089],
         [0.5938345 , 0.56731563, 0.80982999, 0.4754457 , 0.81614833],
         [0.86809126, 0.00468082, 0.10043566, 0.84422456, 0.96802587],
         [0.48544154, 0.76221579, 0.55794415, 0.18294985, 0.88781897]],

        [[0.83912678, 0.47185968, 0.40012494, 0.80582715, 0.94006158],
         [0.58514992, 0.81623245, 0.46327403, 0.90536525, 0.69053979]

In [42]:
x = c[1][1]
x

array([[0.83912678, 0.47185968, 0.40012494, 0.80582715, 0.94006158],
       [0.58514992, 0.81623245, 0.46327403, 0.90536525, 0.69053979],
       [0.29487007, 0.37896638, 0.02257707, 0.52655436, 0.04295077],
       [0.02267775, 0.90448899, 0.69006785, 0.0109071 , 0.22551093]])

In [44]:
y = c[0,1]
y

array([[0.53976314, 0.53120056, 0.57738488, 0.01169558, 0.77128118],
       [0.85126244, 0.04283652, 0.03726557, 0.75749606, 0.24630321],
       [0.89218131, 0.81023714, 0.98536603, 0.09309156, 0.85504858],
       [0.86363777, 0.56479927, 0.89458388, 0.10239363, 0.68995892]])

In [45]:
# Add elements of x and y toguether 

print(np.add(x,y))

[[1.37888991 1.00306024 0.97750982 0.81752273 1.71134276]
 [1.43641235 0.85906898 0.5005396  1.66286132 0.93684299]
 [1.18705138 1.18920352 1.0079431  0.61964592 0.89799936]
 [0.88631552 1.46928826 1.58465174 0.11330074 0.91546985]]


In [46]:
# Substract elements of x from elements of y

print(np.subtract(y,x))

[[-0.29936364  0.05934088  0.17725995 -0.79413156 -0.16878039]
 [ 0.26611252 -0.77339593 -0.42600845 -0.14786919 -0.44423658]
 [ 0.59731124  0.43127076  0.96278896 -0.4334628   0.81209781]
 [ 0.84096001 -0.33968972  0.20451603  0.09148653  0.46444799]]


In [47]:
# Multiply elements of x and y toguether

print(np.multiply(x, y))

[[0.4529297  0.25065213 0.23102609 0.00942462 0.7250518 ]
 [0.49811614 0.03496456 0.01726417 0.68581061 0.17008216]
 [0.26307757 0.30705263 0.02224667 0.04901777 0.036725  ]
 [0.01958536 0.51085472 0.61732358 0.00111682 0.15559328]]


In [48]:
# Divide elements of y by elements of x

print(np.divide(y,x))

[[6.43243846e-01 1.12575958e+00 1.44301149e+00 1.45137626e-02
  8.20458150e-01]
 [1.45477665e+00 5.24807887e-02 8.04395928e-02 8.36674551e-01
  3.56682136e-01]
 [3.02567602e+00 2.13801854e+00 4.36445555e+01 1.76793826e-01
  1.99076417e+01]
 [3.80830379e+01 6.24440186e-01 1.29637090e+00 9.38779328e+00
  3.05953655e+00]]
